name: faceted-docs
channels:
    - conda-forge
dependencies:
    - python=3.6
    - cartopy=0.15.1
    - jupyter
    - matplotlib=2.2
    - nc-time-axis
    - numpy
    - pytest
    - ipython=7.2.0
    - cftime=1.0.3.4
    - sphinx=1.8.2
    - numpydoc=0.8.0
    - sphinx-gallery=0.2.0
    - sphinx_rtd_theme=0.4.2
    - netCDF4=1.4.2
    - pip:
      - coveralls
      - pytest-cov
      - git+git://github.com/pydata/xarray.git
