name: faceted-docs
channels:
    - conda-forge
dependencies:
    - python==3.9
    - cartopy
    - jupyter
    - matplotlib
    - nc-time-axis
    - numpy
    - pip
    - pooch
    - pytest
    - scipy
    - ipython
    - cftime
    - sphinx
    - numpydoc
    - sphinx-gallery
    - sphinx_rtd_theme
    - netCDF4
    - xarray
    - pip:
      - coveralls
      - pytest-cov
