name: test_env
channels:
    - conda-forge
dependencies:
    - python=3.6
    - black
    - cartopy
    - jupyter
    - matplotlib
    - numpy
    - pip
    - pytest
    - scipy
    - pip:
      - coveralls
      - pytest-cov
