name: test
channels:
    - conda-forge
dependencies:
    - black
    - flake8
    - jupyter
    - matplotlib
    - numpy
    - pip
    - pytest
    - python==3.7
    - scipy
    - pip:
      - coveralls
      - pytest-cov
