name: faceted test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7"]#, "3.8", "3.9"]
        os: [ubuntu-latest]
        platform: [x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Create conda environment
      shell: bash -l {0}
      run: |
        conda env create --file ci/environment.yml
        source activate test
        pip install -v -e . --no-deps
        conda info --all
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        source activate test
        pytest -vv faceted --cov=faceted --cov-report=xml

    - name: Coveralls parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
