name: faceted-ci

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest]
        platform: [x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Create conda environment
      shell: bash -l {0}
      run: |
        conda env create --file ci/environment.yml
        source activate test
        pip install -v -e . --no-deps

    - name: Environment information
      shell: bash -l {0}
      run: |
        source activate test
        conda info --all
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        source activate test
        pytest -vv faceted --cov=faceted --cov-report=xml

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests,${{ matrix.python-version }}
        name: codecov-umbrella
        fail_ci_if_error: false

  sphinx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7"]
        os: [ubuntu-latest]
        platform: [x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Create conda environment
      shell: bash -l {0}
      run: |
        conda env create --file doc/environment.yml
        source activate faceted-docs
        pip install -v -e . --no-deps

    - name: Environment information
      shell: bash -l {0}
      run: |
        source activate faceted-docs
        conda info --all
        conda list

    - name: Test that the documentation builds
      shell: bash -l {0}
      run: |
        source activate faceted-docs
        cd doc
        sphinx-build -n -j auto -b html -d _build/doctrees . _build/html

  black:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7"]
        os: [ubuntu-latest]
        platform: [x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge
    
    - name: Install black
      shell: bash -l {0}
      run: conda create --name black python=3.7 black

    - name: black --check .
      shell: bash -l {0}
      run: |
        source activate black
        black --check --exclude _version.py faceted

  flake8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7"]
        os: [ubuntu-latest]
        platform: [x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge
        
    - name: Install flake8
      shell: bash -l {0}
      run: conda create --name flake8 python=3.7 flake8

    - name: flake8
      shell: bash -l {0}
      run: |
        source activate flake8
        flake8
